sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf LDM-682.pdf --upload --lsstdoc LDM-682.tex --env=travis --ltd-product ldm-682"
env:
  global:
    # LSST the Docs credentials
    - secure: "Zyl7/if6VxpEG4ht7FNcEQi8In9J9j6DR4HF2QLTTNq8sZPKPCk4xQHpEWRYOoEc6mWlnwzEM/7LBDDeRu0GuTExO90OGYrrL2XuLj0VR+kX9RiEfZtmkt7epLBOGdczDHzgNDKGomTm1lVgND9wUkiy6DlxMK43YtrhlKqsEAX6v6pCGHX9xqjbP0TQstXZf+SrDEB0CbN807GF2gxBHzDLK1ir234K82ulqqoXKCG3xNwrtUL4PJ1Y29IC7TryD0Ai0cfWoGdYYf7KLgR1r/yAreHgk9mObulepNuzsMNw2R1eacSyeynhqv0BYuRSHG5jrUVFlbcWF9aCW84axno9cHGKZwjRBDZPqCp8rnNBHIiQMCFmO4j6woq+5ln6Svg0POPry+iV9BJlJVBoZI66jH8eMfcBT77VAiKHoZ2hiXHiyIkszj2mr6zgcj+J3kG4g1g6NpdJtSPTWZ9OlmsRdI7JhRmQ6DTxzySYk0L6uIef+nK4yTQWf7dyBaFnyAxpMw+nDPOu+1EwE2jzpLof1xC0dz1o8/F95+ybT1iQpnkuHNaMax01j1PTq1u/PGHpW4s9NLkgR46Eb6iy2L7mN1Y9oS+cub3Vk06jKP/U7NoHOeRfDTrLn9sY4Ai1hmVO9druuWpuqsEXix55yl2hGknhmIJmgUG+8w34sV8="
    - secure: "Z6s7d9hW1Nopb0OcEdF217BmO4OjH/R+pY672CDSznYD5Snp/UrMNCMxvbx+nJ1e7WGoB/LLg/2goE0FbW3YGfFT2ZZ/G/AP0tLRFR4gzCOmESaNXx+ZydsSI4jiFlUrw07F+TN46DTkbGQSKVfjK6udsUHBs43pGzcW+0d+Y4CoqnLi7GiiGkGlk7R3ctg/VCErsLjXwXtrl5SRKQ3U5bBnMw5fOgk5Dk6jmNPkAnqY6aCnALEyt3JcxOwLxrSzeRxdCRIjkI8B0QNLCQy2VConKD07m7gxG70SzQQxyk5ygw8O/U7Os/bBCNAoQzhvsj2GsXTclA2LGitLss5o6UaValJ6PMlYQrDbkvbxJf3VeIkDuUe8vpN6y4NJGkysEOFP8gmTrUOUwIvWqPL7mIgzlxmpZ2EKf0drHPRA/scpNbJX8PkYrTJdGvG5wqdIY6tc3jWNsYVRc20ki1wA3hj0yxMWapUu/AsKzYrbNZpiIHHP8jTIf3/KMpWNbHJpgmchtY45/HoNTDqUZWP7U9TwkaXHoH72XS+ruYqz2trTATrbkeZva17Ax5KcrqjKcsoDUDDbbVjH3+vrQmxgH6WxHybYXYDdOzThGvHErJ5Wp9hwoexfp826NypxLLsOcCchUG6sq1q4y6vkTHrwPezixBIlY3v1Kz/Dy0Vwu/k="
